
/*
Auto-generated by CVXPYgen on April 30, 2023 at 17:57:19.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 16> Qsqrt;
    std::array<double, 4> Rsqrt;
    std::array<double, 16> A;
    std::array<double, 8> B;
    std::array<double, 4> s_error;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool Qsqrt;
    bool Rsqrt;
    bool A;
    bool B;
    bool s_error;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 84> S;
    std::array<double, 40> U;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 4> d0;
    std::array<double, 2> d1;
    std::array<double, 2> d2;
    std::array<double, 4> d3;
    std::array<double, 2> d4;
    std::array<double, 2> d5;
    std::array<double, 4> d6;
    std::array<double, 2> d7;
    std::array<double, 2> d8;
    std::array<double, 4> d9;
    std::array<double, 2> d10;
    std::array<double, 2> d11;
    std::array<double, 4> d12;
    std::array<double, 2> d13;
    std::array<double, 2> d14;
    std::array<double, 4> d15;
    std::array<double, 2> d16;
    std::array<double, 2> d17;
    std::array<double, 4> d18;
    std::array<double, 2> d19;
    std::array<double, 2> d20;
    std::array<double, 4> d21;
    std::array<double, 2> d22;
    std::array<double, 2> d23;
    std::array<double, 4> d24;
    std::array<double, 2> d25;
    std::array<double, 2> d26;
    std::array<double, 4> d27;
    std::array<double, 2> d28;
    std::array<double, 2> d29;
    std::array<double, 4> d30;
    std::array<double, 2> d31;
    std::array<double, 2> d32;
    std::array<double, 4> d33;
    std::array<double, 2> d34;
    std::array<double, 2> d35;
    std::array<double, 4> d36;
    std::array<double, 2> d37;
    std::array<double, 2> d38;
    std::array<double, 4> d39;
    std::array<double, 2> d40;
    std::array<double, 2> d41;
    std::array<double, 4> d42;
    std::array<double, 2> d43;
    std::array<double, 2> d44;
    std::array<double, 4> d45;
    std::array<double, 2> d46;
    std::array<double, 2> d47;
    std::array<double, 4> d48;
    std::array<double, 2> d49;
    std::array<double, 2> d50;
    std::array<double, 4> d51;
    std::array<double, 2> d52;
    std::array<double, 2> d53;
    std::array<double, 4> d54;
    std::array<double, 2> d55;
    std::array<double, 2> d56;
    std::array<double, 4> d57;
    std::array<double, 2> d58;
    std::array<double, 2> d59;
    std::array<double, 4> d60;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
