
/*
Auto-generated by CVXPYgen on April 30, 2023 at 17:57:19.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static c_int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Qsqrt(0, 1.00000000000000000000);
  cpg_update_Rsqrt(0, 0.00000000000000000000);
  cpg_update_A(0, 0.00000000000000000000);
  cpg_update_B(0, 0.00000000000000000000);
  cpg_update_s_error(0, 20.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<84; i++) {
    printf("S[%lld] = %f\n", i, CPG_Result.prim->S[i]);
  }
  for(i=0; i<40; i++) {
    printf("U[%lld] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<4; i++) {
    printf("d0[%lld] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<2; i++) {
    printf("d1[%lld] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<2; i++) {
    printf("d2[%lld] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<4; i++) {
    printf("d3[%lld] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<2; i++) {
    printf("d4[%lld] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<2; i++) {
    printf("d5[%lld] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<4; i++) {
    printf("d6[%lld] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<2; i++) {
    printf("d7[%lld] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<2; i++) {
    printf("d8[%lld] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<4; i++) {
    printf("d9[%lld] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<2; i++) {
    printf("d10[%lld] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<2; i++) {
    printf("d11[%lld] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<4; i++) {
    printf("d12[%lld] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<2; i++) {
    printf("d13[%lld] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<2; i++) {
    printf("d14[%lld] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<4; i++) {
    printf("d15[%lld] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<2; i++) {
    printf("d16[%lld] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<2; i++) {
    printf("d17[%lld] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<4; i++) {
    printf("d18[%lld] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<2; i++) {
    printf("d19[%lld] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<2; i++) {
    printf("d20[%lld] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<4; i++) {
    printf("d21[%lld] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<2; i++) {
    printf("d22[%lld] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<2; i++) {
    printf("d23[%lld] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<4; i++) {
    printf("d24[%lld] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<2; i++) {
    printf("d25[%lld] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<2; i++) {
    printf("d26[%lld] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<4; i++) {
    printf("d27[%lld] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<2; i++) {
    printf("d28[%lld] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<2; i++) {
    printf("d29[%lld] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<4; i++) {
    printf("d30[%lld] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<2; i++) {
    printf("d31[%lld] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  for(i=0; i<2; i++) {
    printf("d32[%lld] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<4; i++) {
    printf("d33[%lld] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  for(i=0; i<2; i++) {
    printf("d34[%lld] = %f\n", i, CPG_Result.dual->d34[i]);
  }
  for(i=0; i<2; i++) {
    printf("d35[%lld] = %f\n", i, CPG_Result.dual->d35[i]);
  }
  for(i=0; i<4; i++) {
    printf("d36[%lld] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  for(i=0; i<2; i++) {
    printf("d37[%lld] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  for(i=0; i<2; i++) {
    printf("d38[%lld] = %f\n", i, CPG_Result.dual->d38[i]);
  }
  for(i=0; i<4; i++) {
    printf("d39[%lld] = %f\n", i, CPG_Result.dual->d39[i]);
  }
  for(i=0; i<2; i++) {
    printf("d40[%lld] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  for(i=0; i<2; i++) {
    printf("d41[%lld] = %f\n", i, CPG_Result.dual->d41[i]);
  }
  for(i=0; i<4; i++) {
    printf("d42[%lld] = %f\n", i, CPG_Result.dual->d42[i]);
  }
  for(i=0; i<2; i++) {
    printf("d43[%lld] = %f\n", i, CPG_Result.dual->d43[i]);
  }
  for(i=0; i<2; i++) {
    printf("d44[%lld] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  for(i=0; i<4; i++) {
    printf("d45[%lld] = %f\n", i, CPG_Result.dual->d45[i]);
  }
  for(i=0; i<2; i++) {
    printf("d46[%lld] = %f\n", i, CPG_Result.dual->d46[i]);
  }
  for(i=0; i<2; i++) {
    printf("d47[%lld] = %f\n", i, CPG_Result.dual->d47[i]);
  }
  for(i=0; i<4; i++) {
    printf("d48[%lld] = %f\n", i, CPG_Result.dual->d48[i]);
  }
  for(i=0; i<2; i++) {
    printf("d49[%lld] = %f\n", i, CPG_Result.dual->d49[i]);
  }
  for(i=0; i<2; i++) {
    printf("d50[%lld] = %f\n", i, CPG_Result.dual->d50[i]);
  }
  for(i=0; i<4; i++) {
    printf("d51[%lld] = %f\n", i, CPG_Result.dual->d51[i]);
  }
  for(i=0; i<2; i++) {
    printf("d52[%lld] = %f\n", i, CPG_Result.dual->d52[i]);
  }
  for(i=0; i<2; i++) {
    printf("d53[%lld] = %f\n", i, CPG_Result.dual->d53[i]);
  }
  for(i=0; i<4; i++) {
    printf("d54[%lld] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<2; i++) {
    printf("d55[%lld] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  for(i=0; i<2; i++) {
    printf("d56[%lld] = %f\n", i, CPG_Result.dual->d56[i]);
  }
  for(i=0; i<4; i++) {
    printf("d57[%lld] = %f\n", i, CPG_Result.dual->d57[i]);
  }
  for(i=0; i<2; i++) {
    printf("d58[%lld] = %f\n", i, CPG_Result.dual->d58[i]);
  }
  for(i=0; i<2; i++) {
    printf("d59[%lld] = %f\n", i, CPG_Result.dual->d59[i]);
  }
  for(i=0; i<4; i++) {
    printf("d60[%lld] = %f\n", i, CPG_Result.dual->d60[i]);
  }

  return 0;

}
